<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9ockPu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9ockPu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF9ockPu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF9ockPu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF9ockPu\App_KernelDevDebugContainer([
    'container.build_hash' => 'F9ockPu',
    'container.build_id' => 'b0f377e7',
    'container.build_time' => 1584914203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9ockPu');
