<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5F3d7YV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5F3d7YV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5F3d7YV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5F3d7YV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5F3d7YV\App_KernelDevDebugContainer([
    'container.build_hash' => '5F3d7YV',
    'container.build_id' => '6c55e246',
    'container.build_time' => 1584301996,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5F3d7YV');
